<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Blog.Web-8cadf678-27e0-4196-acde-e86c5f2290b2</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Shared\ActivityExtensions.cs">
            <Link>Shared\ActivityExtensions.cs</Link>
        </Compile>
        <Compile Include="..\Shared\MigrateDbContextExtensions.cs">
            <Link>Shared\MigrateDbContextExtensions.cs</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
